export const PAYMENT_CREATE_REQUEST = "PAYMENT_CREATE_REQUEST";
export const PAYMENT_CREATE_SUCCESS = "PAYMENT_CREATE_SUCCESS";
export const PAYMENT_CREATE_FAIL = "PAYMENT_CREATE_FAIL";

export const PAYMENT_DETAILS_REQUEST = "PAYMENT_DETAILS_REQUEST";
export const PAYMENT_DETAILS_SUCCESS = "PAYMENT_DETAILS_SUCCESS";
export const PAYMENT_DETAILS_FAIL = "PAYMENT_DETAILS_FAIL";

export const PAYMENT_PAY_REQUEST = "PAYMENT_PAY_REQUEST";
export const PAYMENT_PAY_SUCCESS = "PAYMENT_PAY_SUCCESS";
export const PAYMENT_PAY_FAIL = "PAYMENT_PAY_FAIL";
export const PAYMENT_PAY_RESET = "PAYMENT_PAY_RESET";
